install:
  - git clone --branch v1.0.2 --depth 1 https://github.com/bats-core/bats-core.git bats
  - git clone --branch v1.0.1 --depth 1 https://github.com/jasonkarns/bats-mock.git
script:
  - shellcheck -x src/**/*.sh
  - PATH="./bats/bin:$PATH" bats test/*
before_deploy:
  - tar --exclude prepare*.sh -C src -cvzf blockchain-build-lib.tgz .
  - tar --exclude pipeline-PREPARE.sh --exclude chaincode-pipeline -C scripts -cvzf sample-blockchain-build-lib.tgz .
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "blockchain-build-lib.tgz"
    - "sample-blockchain-build-lib.tgz"
  skip_cleanup: true
  on:
    tags: true
