install:
  - git clone --branch v1.0.2 --depth 1 https://github.com/bats-core/bats-core.git bats
  - git clone --branch v1.0.1 --depth 1 https://github.com/jasonkarns/bats-mock.git
script:
  - shellcheck src/**/*.sh
  - PATH="./bats/bin:$PATH" bats test/*
