---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-BUILD.sh
- name: "DEPLOY"
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: BLOCKCHAIN_SERVICE_INSTANCE
    value: ${BLOCKCHAIN_SERVICE_INSTANCE}
    type: text
  - name: CLOUDANT_SERVICE_INSTANCE
    value: ${CLOUDANT_SERVICE_INSTANCE}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh